### PR TITLE
check json-schema

### PR DESCRIPTION
**Pull request by tschm**
@webknjaz I check now the json-schema for workflows in .github/workflows... I guess we should also check the action.yml file?

### CODE REVIEW

**Comment by tschm** [comment]
actually I am checking now the action and the workflows

**Comment by webknjaz** [comment]
I thought `files:` is not mandatory. Have you checked?

**Comment by tschm** [comment]
yes, it can be dropped. I am slightly surprised that when I turn on

verbose: true

It would not list all files that are checked.

**Comment by tschm** [comment]
there is now also https://github.com/python-jsonschema/check-jsonschema/issues/312#issuecomment-1694677258

**Comment by sirosen** [comment]
I think you'll want `args: ["--verbose"]` rather than or in addition to `verbose: true`. The difference is between turning up verbosity for `pre-commit` and turning up verbosity for `check-jsonschema` itself.

In this context I'm not 100% sure that `pre-commit`'s `verbose: true` is what you want. `pre-commit` suppresses most output from hooks _on hook success_ unless `verbose: true` is set. I've rarely seen people turn on this flag. I think the more common usage is that you might run `pre-commit run -a -v` if you want to see more output across the board.

I'll be working on https://github.com/python-jsonschema/check-jsonschema/issues/312 regardless, but it will probably be pretty noisy if you set both verbosity flags in the config. It would mean a lot of output each time you run `git commit` if you have the hooks installed.

**Comment by tschm** [comment]
@sirosen Thank you for your swift action on a Sunday :-) For my experiments I needed both the
verbose: true and the args: ["--verbose"] to get the output as seen in https://github.com/tschm/token-mint-action/actions/runs/5995471871/job/16258533186

I am very happy with the output but somewhat I think it should be enough to specify one of these two...Maybe something for 0.26.3?

**Comment by sirosen** [comment]
I mentioned this on the `check-jsonschema` issue, but I'll share some doc links here.
These are two different tools. They have their own verbosity options.

`pre-commit` defines `verbose: true` and `args: [...]`: https://pre-commit.com/#pre-commit-configyaml---hooks

`check-jsonschema` defines `--verbose`: https://check-jsonschema.readthedocs.io/en/stable/usage.html

There isn't any change to this situation that _can_ be made by `check-jsonschema` as far as I know, so I don't have any intention to do more about it.

---

On a separate note, I looked briefly to see if the pre-commit action would let you pass `-v` to its invocation -- as I said above, I don't think it's a good idea to set `verbose: true` since it produces more noise every time the hook runs -- and I did notice that it states that it is deprecated in favor of pre-commit.ci . So you may want to consider replacing the action either with pre-commit.ci or a combination of `pip install pre-commit; pre-commit run -a -v` in order to get onto a more supported path.

**Comment by tschm** [comment]
ah, that's a good idea. So I will update my centralized workflows and add the -v flag in the pre-commit run

**Comment by tschm** [comment]
@iamazeem @webknjaz @sirosen this could be merged now...

**Pull request merged**
